language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install automake libtool libsnmp-dev bison make gcc flex git libglib2.0-dev libfl-dev snmp-mibs-downloader
  - sudo pip install cpp-coveralls
  - ./autogen.sh

script:
  - ./configure CFLAGS='-g -O0 -fprofile-arcs -ftest-coverage'
  - make && sudo make install
  - cd tests/
  - ./RunTests.sh
  - cd ..

after_success:
  - coveralls --exclude src/docsis_lex.c --exclude src/docsis_yy.c --gcov-options '\-lp'